language: java

sudo: false

env:
   global:
      secure: "R8VOBETXlqtGbrJ+6pG0pQtiYl28aR6AgScbILg+3IflnHkXPIIM8Ysf1A4iYXWcW3bg8sPSjLIWHcHg3pJ0Cht/aRzHHF/0wY/Qv1HY02Vno5A350NRM8AiEGKf7Ge0hRFgwhcDMNzuOOsoT6Jlfrn+RoLNHgzp+gNv6dytiTIYSNjp41RCHvrMjtOOTyCQDlPDn/n+QJeeyfDP+b1jFONmtCs4JJX9ZSMWK3x9EUUp0ZQ4VCTSv3IV7tuv/oqjNQOdWnGyUmUkLvHL8PYeYCdByzQn2B4ZbBYUFDqU53c15xrLQ1D78T5yQr1ZdTR5saRDzaH0i4q2jFD9vOiz1tU9Nsu7fVSWIq5zsyyVjzNUhY4jZdvH+mai+TLp3FhMXL9wOE9qb6KvZRbHn+gSd+XZpPRojntxz7YlGaJkLGopN6BNfQ9Y+7KeUmEbUGbW3uk+oc0isYFSZYxU7kVJiQ3nCJsdUdrVcmgZbRCPN1jbRTHfef8/zsF0ub+Z3OJmpWT10q17p8gxLGRP1PjBwlNhpHSI1vGoX4BhHafx9z6ItcFJC+wTThA2l6scoXqhARChgIqspFEjfh7CG3CPRyq540GNVqyMRDHVDI+7jPWJlyZK/p9xZjDFZ1t4vl4qipngIxgP8cwuiirIDxmfKN5dfcr+tL7YLWgvhpwYv1E="

before_install:
 - wget -O maven.tar.gz http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
 - mkdir maven
 - cd maven ; tar --strip-components 1 -xzf ../maven.tar.gz ; cd ..
 - chmod a+x maven/bin/mvn
 - export M2_HOME=$PWD/maven
 - export PATH=$PWD/maven/bin:${PATH}
 - hash -r

before_script:
 - export M2_HOME=$PWD/maven
 - export PATH=$PWD/maven/bin:${PATH}
 - hash -r

install:
 - cd runtime && mvn package && cd ..

script: mvn package -B

after_success:
 - for i in `ls products/org.eclipse.packagedrone.server/target/*.{zip,deb}`; do curl -X PUT --data-binary @$i "http://deploy:$DKEY@packagedrone.eclipse.org/api/v2/upload/channel/packagagedrone-ci/$(basename $i)?travis:buildNumber=$TRAVIS_BUILD_NUMBER&travis:jobNumber=$TRAVIS_JOB_NUMBER&travis:repoSlug=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0])' "$TRAVIS_REPO_SLUG")"; done

jdk:
  - oraclejdk8

addons:
   apt:
      packages:
         - rpm
         - liburi-perl

